version: "3.8"

services:
  
  db:
    restart: always
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  api:
    build:
        context: ./api
        dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: ['sh', 'start-project.sh']
    ports: 
      - 8080:8080
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    environment: 
      - VUE_APP_URL=http://0.0.0.0:8080/
      - VUE_APP_BASE_URL=http://0.0.0.0:8000/

volumes: 
  node_modules